#!/bin/bash

echo "$(pwd)"

if {
#  [[ "$(type framework 2>&1)" =~ "non trouvé" ]] ||
#  [[ "$(type framework 2>&1)" =~ "not found" ]] ||
  [[ ! -d "$(pwd)/bash-aliases-framework" ]]
};then
  git clone git@github.com:nicolachoquet06250/bash-aliases-framework.git
fi

if {
#  [[ "$(type clipboard 2>&1)" =~ "non trouvé" ]] ||
#  [[ "$(type clipboard 2>&1)" =~ "not found" ]] ||
  [[ ! -d "$(pwd)/bash-alias-clipboard" ]]
};then
  git clone git@github.com:nicolachoquet06250/bash-alias-clipboard.git
fi

if [[ ! -d "${HOME}/.bash-aliases-norsys" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-alias-clipboard"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-aliases-norsys";
fi

file_path=".bash-aliases-norsys/.bash_aliases"

source_1="source \"\${HOME}/${file_path}\""
source_2="source \"~/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"
bash_aliases_content="$(cat "${bash_aliases_path}")"

if {
  [[ ! "${bash_aliases_content}" =~ $source_1 ]] &&
  [[ ! "${bash_aliases_content}" =~ $source_2 ]]
};then
  echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}"
fi