#!/bin/bash

if [[ ! -d "$(pwd)/bash-aliases-framework" ]];then
  git clone git@github.com:nicolachoquet06250/bash-aliases-framework.git
fi

rm -rf "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout"
ln -s "$(pwd)/bash-aliases-framework/.githooks/post-checkout" "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout"
echo "${SUDO_PASSWD}" | sudo -S chmod +x "$(pwd)/bash-aliases-framework/.githooks/post-checkout"

# shellcheck disable=SC1090
. "$(pwd)/bash-aliases-framework/.git/hooks/post-checkout" "install-script"

if [[ ! -d "$(pwd)/bash-alias-clipboard" ]];then
  git clone git@github.com:nicolachoquet06250/bash-alias-clipboard.git
fi

rm -rf "$(pwd)/bash-alias-clipboard/.git/hooks/post-checkout"
ln -s "$(pwd)/bash-alias-clipboard/.githooks/post-checkout" "$(pwd)/bash-alias-clipboard/.git/hooks/post-checkout"
echo "${SUDO_PASSWD}" | sudo -S chmod +x "$(pwd)/bash-alias-clipboard/.githooks/post-checkout"

# shellcheck disable=SC1090
. "$(pwd)/bash-alias-clipboard/.git/hooks/post-checkout" "install-script"

if [[ ! -d "${HOME}/.bash-aliases-norsys" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-aliases-norsys"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-aliases-norsys";
fi

file_path=".bash-aliases-norsys/.bash_aliases"

source_1="source \"\${HOME}/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"

file_content="$(cat "${bash_aliases_path}")"
IFS=$'\n'
read -rd '' -a lines <<<"${file_content}"

[[ "${lines[*]}" != *"$source_1"* ]] && echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}" || echo "" >> /dev/null